global using Weight = float;
global using SimdVector = System.Numerics.Vector<float>;
global using SimdVectorHelper = System.Numerics.Vector;
global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Collections.Frozen;
global using System.Diagnostics;
global using System.Numerics.Tensors;
global using System.Linq;
